pipeline {
    agent any
    tools {
        maven 'Maven 3.9.7' // Make sure this is your Maven version
    }
    environment {
        PATH = "/usr/local/sdkman/candidates/maven/current/bin:${env.PATH}" // Adjust if needed
    }
    stages {
        stage('Clean Workspace') {
            steps {
                sh 'mvn clean'
            }
        }
        stage('Checkout') {
            steps {
                git 'https://github.com/Blaundos/sample-project.git'
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }
        stage('Code Review') { 
            steps {
                sh 'mvn checkstyle:check'  // Adjust if using a different code analysis tool
            }
        }
        stage('Unit Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Package') {
            steps {
                sh 'mvn -X package' // Enable debug logging
                echo "WAR file name: $(ls target/*.war)" 
            }
        }
        stage('Deploy to Local Tomcat') {
            steps {
                script {
                    def warFileName = sh(script: 'ls target/*.war', returnStdout: true).trim()
                    echo "WAR file name: ${warFileName}"
                    def tomcatWebapps = sh(script: 'echo $CATALINA_HOME/webapps/', returnStdout: true).trim() 
                    echo "Tomcat webapps directory: ${tomcatWebapps}"
                    sh "cp target/${warFileName} ${tomcatWebapps}"
                }
            }
        }
    }
}
